version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - packages/backend/.env
    ports:
      - '3000:3000'
  app:
    container_name: app
    build:
      context: .
      dockerfile: packages/app/Dockerfile
    env_file:
      - packages/app/.env
    ports:
      - '80:80'
